const constants = {
    SUGESTED_CITY_LOADING: "SUGESTED_CITY_LOADING",
    SUGESTED_CITY_SUCCESS:"SUGESTED_CITY_SUCCESS",
    SUGESTED_CITY_FAILED:"SUGESTED_CITY_FAILED"

} 

export default constants;